[package]
name = "fdi"
version = "0.1.0"
authors = ["Danny Woods <dannywoodz@yahoo.co.uk>"]

[build-dependencies]
pkg-config = "0.3.9"
cc = "1.0.4"

[dependencies]
walkdir = "2"
rayon = "0.9"
regex = "0.2"
libc = "0.2"
getopts = "0.2"
log4rs = "0.8.0"
log = "0.4"
