/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fdi_FileID */

#ifndef _Included_fdi_FileID
#define _Included_fdi_FileID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fdi_FileID
 * Method:    id
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_fdi_FileID_id
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
